spring:
  datasource:
    url: jdbc:mariadb://korjjh1216.csqivjbiawjj.ap-northeast-2.rds.amazonaws.com:3306/korjjh1216
    driver-class-name: org.mariadb.jdbc.Driver
    username: korjjh1216
    password: wlsgud12
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

UserController:
  signup: Creates user and returns its JWT token
  login: Authenticates user and returns its JWT token